language: node_js
node_js:
  - node
cache:
  directories:
    - node_modules
before_install:
  - openssl aes-256-cbc -K $encrypted_6f9c164d0bb4_key -iv $encrypted_6f9c164d0bb4_iv -in github_deploy_key.enc -out github_deploy_key -d
  - chmod 600 github_deploy_key
  - eval $(ssh-agent -s)
  - ssh-add github_deploy_key
install:
  - npm install
script:
  - npm run build -- --mode production
deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy_to_git.sh 'dist' 'git@github.com:softfair/Jira-Issue-Card-Printer.git' 'gh-pages'
  on:
    branch: master
    condition: "$TRAVIS_REPO_SLUG = softfair/Jira-Issue-Card-Printer"
